/**
 * Plano-Pizza-and-Pies - Backend Server
 * Auto-generated by Module Library Assembler
 * 
 * Run: npm install && npm run dev
 */

const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
require('dotenv').config();

const app = express();

// ============================================
// MIDDLEWARE
// ============================================

app.use(helmet({ contentSecurityPolicy: false }));
app.use(cors({ origin: true, credentials: true }));
app.use(morgan('dev'));
app.use(express.json({ limit: '50mb' }));
app.use(express.urlencoded({ extended: true, limit: '50mb' }));

// ============================================
// MODULE ROUTES (Auto-Wired)
// ============================================

const authRoutes = require('./modules/auth/routes/auth.js');

// Register routes
app.use('/api/auth', authRoutes);

// ============================================
// BRAIN & HEALTH ROUTES (Admin System)
// ============================================

const brainRoutes = require('./routes/brain');
const healthRoutes = require('./routes/health');

app.use('/api/brain', brainRoutes);
app.use('/api/health', healthRoutes);

// Quick health check (legacy)
app.get('/health', (req, res) => {
  res.json({
    status: 'ok',
    project: 'Plano-Pizza-and-Pies',
    timestamp: new Date().toISOString(),
    modules: 1
  });
});

// ============================================
// ERROR HANDLING
// ============================================

app.use((err, req, res, next) => {
  console.error('Error:', err.message);
  res.status(err.status || 500).json({
    error: err.message || 'Internal server error'
  });
});

// 404 handler
app.use((req, res) => {
  res.status(404).json({ error: 'Not found', path: req.path });
});

// ============================================
// START SERVER
// ============================================

const PORT = process.env.PORT || 5000;

app.listen(PORT, () => {
  console.log('');
  console.log('🚀 Plano-Pizza-and-Pies backend running on port ' + PORT);
  console.log('   Health: http://localhost:' + PORT + '/health');
  console.log('   API:    http://localhost:' + PORT + '/api');
  console.log('');
  console.log('📦 Loaded modules (1):');
  console.log('   ✅ auth');
});

module.exports = app;
